### PR TITLE
prevent trying to setState on unmounted VirtualList + checking for undefined state before comparison

### LINKED ISSUE #59: throttleWithRAF causes setState warning
Unmounting a component that uses react-virtual-list may cause it to produce the following warning:

`
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the vlist component.
`

If I disable `throttleWithRAF`, the warning is gone, because there is no longer any asynchronicity. The vlist component should not call setState if it is no longer mounted.

### LINKED ISSUE #65: Check state
You don't check whether `state` from `getVisibleItemBounds()` is undefined before comparison:
problem

### PR DESCRIPTION
**Pull request by Ramshackle-Jamathon**
fixes #59 
fixes #65

### CODE REVIEW

**Comment by Ramshackle-Jamathon** [comment]
@developerdizzle sorry if this PR is a bit abrupt, I just wanted to fix some of the warnings/errors I ran into using this super rad component!

**Comment by Ramshackle-Jamathon** [comment]
@developerdizzle yoooo! you mind taking a look-see at this PR some time?

**Comment by developerdizzle** [comment]
@Ramshackle-Jamathon Can you add a patch version bump in package.json?

**Comment by konradd93** [comment]
Still not working, becouse you changed only file src/VirtualList.js, but in package.json is "main": "lib/VirtualList.js".
next time check your change really solve the problem before creating the pull request, please. ;)

**Comment by Ramshackle-Jamathon** [comment]
@konradd93 my bad dude, I did check that my changes fixed the problem but I didn't include the build artifacts in my PR (the lib/ directory you're talking about). I should've ran the build when I pushed the version bump.

@developerdizzle It should be resolved by running the build and releasing a patch

**Comment by developerdizzle** [comment]
Version 2.2.4 has been published!  My apologies for the delay.

**Pull request merged**
