### PR TITLE
Initial item count

### PR DESCRIPTION
**Pull request by jordansexton**
This is just a WIP refactoring of your branch. I tried to break it up if you want to cherry pick around it. This should fix the problems with isomorphic rendering I mentioned in the comments on #18 while also avoiding mismatching render checksums by only calling `getVirtualItems` first from `componentDidMount`.

### CODE REVIEW

**Comment by jordansexton** [comment]
I'm currently testing a build of this in my isomorphic application, substituting it in for the code from #15

**Comment by jordansexton** [comment]
I just noticed I'm actually using `initialVisibleItems` instead of `initialVisibleItemCount`. The latter is more explicit, but is definitely lengthy.

**Comment by developerdizzle** [comment]
This looks great, although I would definitely prefer the more explicit `initialVisibleItemCount` property name.  We could probably shorten it to `initialItemCount` if you'd prefer.

**Comment by jordansexton** [comment]
`initialItemCount` sounds good to me (especially since they're not inherently visible, just rendered). Unfortunately, there are actually some problems with this implementation that I started resolving but didn't finish this weekend. I'll update the PR soon, just got busy with a project temporarily.

**Comment by developerdizzle** [comment]
Sounds good; take your time.  I've been busy myself and neglecting this project as it is =/

**Comment by jordansexton** [comment]
Haha it happens. I'm using the version from #15 with `initialItems` already [in production](https://stylisted.com/stylists), so I just need to refactor a bit.

**Comment by quicksnap** [comment]
Any update with this? Server rendering is a priority for me as well.

**Comment by quicksnap** [comment]
@jordansexton sorry to bug again--I'm curious if you're still using #15 in production? To save some time I'm going to fork off that and see how it goes.

**Comment by jordansexton** [comment]
@quicksnap No worries, and sorry for the absentee PR here. I've just been swamped with work...

I do use this [in production](https://stylisted.com) and have for the last few months. I also [merged the latest](https://github.com/jordansexton/react-virtual-list/pull/1) from here into my fork's master just now to update it.

I will still revise this in line with @developerdizzle's desire to have an `initialItem` count rather than an array, it's just taking me a while to get around to it.

**Comment by jordansexton** [comment]
SSR works by setting `firstIndex`/`lastIndex` now, so I'm closing this. I can share my specific implementation (which is based on a heavily cut down version of this library) if desired.

**Comment by developerdizzle** [comment]
@jordansexton I'd love to see it, at least for my own learning purposes!  Also - are you using v2 in production?  If so, I'm curious how the new HOC convention has been for you, compared to v1.

**Comment by jordansexton** [comment]
@developerdizzle This is our full implementation (in production @ https://stylisted.com/stylists).

https://gist.github.com/jordansexton/10cc469c2dbd872585c45ebaf6053a8d

There's obviously a lot of extraneous stuff for immutability, isomorphism, performance optimization, and reuse of many of the mixins and other functions throughout our app.

**Comment by jordansexton** [comment]
Misc notes:

- The architecture is a little abstract, but we use mixins to allow many components to respond to resize and scroll events on the same event listener with throttling.
- All of our React component states (and Redux store state and individual props values) have been replaced with Immutable, which has significantly improved performance across the board, but especially with this VirtualList implementation.
- Disabling `pointerEvents` is really useful to prevent jank on hover/touch events on the list, especially on mobile.

**Comment by jordansexton** [comment]
Overall, I think the HOC architecture is great. I would love to try out a version that uses `transformY`, which I haven't had time to figure out yet.

**Comment by developerdizzle** [comment]
Nice, thanks for sharing this!  I'm going to have to take some time to parse through it, but I do think things like disabling `pointer-events` would be great to list as best practices in the README.

**Comment by jordansexton** [comment]
Sure thing. I got the idea from [seatgeek/react-infinite](https://github.com/seatgeek/react-infinite), but just debounced so it doesn't set the component state and cause rerendering, or have to manage timeouts.

**Pull request closed without merging**
